-- ANIMAL_INS 테이블에서 ANIMAL_TYPE 컬럼 선택 후 카운트
SELECT ANIMAL_TYPE, COUNT(*) FROM ANIMAL_INS
-- 조건: ANIAML_TYPE이 'Cat' 또는 'Dog'인 로우
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
-- ANIMAL_TYPE 별로 묶어서 계산
GROUP BY ANIMAL_TYPE
-- ANIMAL_TYPE 순서로 정렬
ORDER BY ANIMAL_TYPE