-- INS라는 이름으로 ANIMAL_INS 테이블의 NAME, DATETIME 컬럼 선택
SELECT INS.NAME, INS.DATETIME FROM ANIMAL_INS AS INS
-- OUTS라는 이름으로 ANIMAL_OUTS 테이블 LEFT JOIN
LEFT JOIN ANIMAL_OUTS AS OUTS
-- JOIN 조건: INS와 OUTS의 ID
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
-- 조건: OUTS의 ID기 NULL인 것
WHERE OUTS.ANIMAL_ID IS NULL
-- INS의 DATETIME 기준으로 오름차순 정렬
ORDER BY INS.DATETIME
-- 제한: 3개
LIMIT 3;