-- ANIMAL_OUTS 테이블에서 DATETIME의 HOUR를 HOUR 컬럼 명으로 선택, 개수 카운트
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
-- 조건: 시간이 9시 이상 20시 미만인 것
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
-- 시간으로 그룹화
GROUP BY HOUR(DATETIME)
-- 시간으로 오름차순 정렬
ORDER BY HOUR(DATETIME);