-- 풀이1: NOT IN (Sub Query)
-- ANIMAL_OUTS 테이블의 ANIMAL_IDD, NAME 컬럼 선택
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS
-- 조건: 선택한 ANIMAL_ID가 ANIMAL_INS 테이블의 ANIMAL_ID에 존재하지 않는 것
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
-- ANIMAL_ID 순으로 오름차순 정렬
ORDER BY ANIMAL_ID;

-- 풀이2: LEFT JOIN
-- OUTS라는 이름으로 ANIMAL_OUTS 테이블을의 ID, NAME 컬럼 선택
SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_OUTS AS OUTS
-- INS라는 이름으로 ANIML_INS 테이블을 JOIN
LEFT JOIN ANIMAL_INS AS INS
-- ID를 기준으로 OUTTER JOIN
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
-- 조건: OUTTER JOIN 결과에서 INS의 ID가 NULL인 것
WHERE INS.ANIMAL_ID IS NULL
-- OUTS 테이블의 ID 순으로 오름차순 정렬
ORDER BY OUTS.ANIMAL_ID;